steps:
#Build image
- id: 'Build Docker Image'
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'eu.gcr.io/$PROJECT_ID/guestbook_frontend:$COMMIT_SHA', '.' ]
  dir: frontend

#Push to GCR
- id: 'Push Docker Image to GCR'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/$PROJECT_ID/guestbook_frontend:$COMMIT_SHA']

#Tag with the staging tag in GCR using gcloud
- id: 'Tag Image in GCR With stg tag'
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['container', 'images', 'add-tag', 'eu.gcr.io/$PROJECT_ID/guestbook_frontend:$COMMIT_SHA', 'eu.gcr.io/$PROJECT_ID/guestbook_frontend:stg']

#Update deployment with new image
- id: 'Deploy to GKE staging'
  name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/frontend-stg'
  - 'frontend=eu.gcr.io/$PROJECT_ID/guestbook_frontend:stg'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-north1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=guestbook'

  #Update COMMIT_HASH env varialble
- name: 'eu.gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'env'
  - 'deployment/frontend-stg'
  - 'COMMIT_HASH=$COMMIT_SHA'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-north1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=guestbook'