steps:
#Build image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/guestbook_frontend_stg:$COMMIT_SHA', '.' ]
  dir: frontend
#Push to GCR
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/guestbook_frontend_stg:$COMMIT_SHA"]
#Update deployment with new image
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/frontend'
  - 'frontend=gcr.io/$PROJECT_ID/guestbook_frontend_stg:$COMMIT_SHA'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-north1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=guestbook'