apiVersion: v1
kind: Service
metadata:
  name: frontend-prd
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
    beta.cloud.google.com/load-balancer: '{"service-label": "my-service"}'
  labels:
    app: guestbook
    tier: frontend
    env: prd
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: guestbook
    tier: frontend
    env: prd
