apiVersion: v1
kind: Service
metadata:
  name: frontend-prd
  labels:
    app: guestbook
    tier: frontend
    env: prd
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 80
  selector:
    app: guestbook
    tier: frontend
    env: prd
